# Generated by Django 5.1.6 on 2026-05-04 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_customer_email_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_code',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
