# Generated by Django 5.1.6 on 2026-05-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cart_user_alter_order_user_alter_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_checkout_id',
        ),
    ]
